#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

npx validate-branch-name

cd client
npm run lint:script --staged
npm run lint:styles --staged
# npm run type-check @TODO: enable when lint will be fixed
cd ../server
npm run lint